// SPDX-License-Identifier: GPL-3.0-or-later

/** JSON field names from the pinned A2A messages. */
export const A2A_FIELDS = {
  SendMessageConfiguration: [
    "acceptedOutputModes",
    "taskPushNotificationConfig",
    "historyLength",
    "returnImmediately",
  ],
  Task: ["id", "contextId", "status", "artifacts", "history", "metadata"],
  TaskStatus: ["state", "message", "timestamp"],
  Part: ["text", "raw", "url", "data", "metadata", "filename", "mediaType"],
  Message: [
    "messageId",
    "contextId",
    "taskId",
    "role",
    "parts",
    "metadata",
    "extensions",
    "referenceTaskIds",
  ],
  Artifact: [
    "artifactId",
    "name",
    "description",
    "parts",
    "metadata",
    "extensions",
  ],
  TaskStatusUpdateEvent: ["taskId", "contextId", "status", "metadata"],
  TaskArtifactUpdateEvent: [
    "taskId",
    "contextId",
    "artifact",
    "append",
    "lastChunk",
    "metadata",
  ],
  AuthenticationInfo: ["scheme", "credentials"],
  AgentInterface: ["url", "protocolBinding", "tenant", "protocolVersion"],
  AgentCard: [
    "name",
    "description",
    "supportedInterfaces",
    "provider",
    "version",
    "documentationUrl",
    "capabilities",
    "securitySchemes",
    "securityRequirements",
    "defaultInputModes",
    "defaultOutputModes",
    "skills",
    "signatures",
    "iconUrl",
  ],
  AgentProvider: ["url", "organization"],
  AgentCapabilities: [
    "streaming",
    "pushNotifications",
    "extensions",
    "extendedAgentCard",
  ],
  AgentExtension: ["uri", "description", "required", "params"],
  AgentSkill: [
    "id",
    "name",
    "description",
    "tags",
    "examples",
    "inputModes",
    "outputModes",
    "securityRequirements",
  ],
  AgentCardSignature: ["protected", "signature", "header"],
  TaskPushNotificationConfig: [
    "tenant",
    "id",
    "taskId",
    "url",
    "token",
    "authentication",
  ],
  StringList: ["list"],
  SecurityRequirement: ["schemes"],
  SecurityScheme: [
    "apiKeySecurityScheme",
    "httpAuthSecurityScheme",
    "oauth2SecurityScheme",
    "openIdConnectSecurityScheme",
    "mtlsSecurityScheme",
  ],
  APIKeySecurityScheme: ["description", "location", "name"],
  HTTPAuthSecurityScheme: ["description", "scheme", "bearerFormat"],
  OAuth2SecurityScheme: ["description", "flows", "oauth2MetadataUrl"],
  OpenIdConnectSecurityScheme: ["description", "openIdConnectUrl"],
  MutualTlsSecurityScheme: ["description"],
  OAuthFlows: [
    "authorizationCode",
    "clientCredentials",
    "implicit",
    "password",
    "deviceCode",
  ],
  AuthorizationCodeOAuthFlow: [
    "authorizationUrl",
    "tokenUrl",
    "refreshUrl",
    "scopes",
    "pkceRequired",
  ],
  ClientCredentialsOAuthFlow: ["tokenUrl", "refreshUrl", "scopes"],
  ImplicitOAuthFlow: ["authorizationUrl", "refreshUrl", "scopes"],
  PasswordOAuthFlow: ["tokenUrl", "refreshUrl", "scopes"],
  DeviceCodeOAuthFlow: [
    "deviceAuthorizationUrl",
    "tokenUrl",
    "refreshUrl",
    "scopes",
  ],
  SendMessageRequest: ["tenant", "message", "configuration", "metadata"],
  GetTaskRequest: ["tenant", "id", "historyLength"],
  ListTasksRequest: [
    "tenant",
    "contextId",
    "status",
    "pageSize",
    "pageToken",
    "historyLength",
    "statusTimestampAfter",
    "includeArtifacts",
  ],
  ListTasksResponse: ["tasks", "nextPageToken", "pageSize", "totalSize"],
  CancelTaskRequest: ["tenant", "id", "metadata"],
  GetTaskPushNotificationConfigRequest: ["tenant", "taskId", "id"],
  DeleteTaskPushNotificationConfigRequest: ["tenant", "taskId", "id"],
  SubscribeToTaskRequest: ["tenant", "id"],
  ListTaskPushNotificationConfigsRequest: [
    "tenant",
    "taskId",
    "pageSize",
    "pageToken",
  ],
  GetExtendedAgentCardRequest: ["tenant"],
  SendMessageResponse: ["task", "message"],
  StreamResponse: ["task", "message", "statusUpdate", "artifactUpdate"],
  ListTaskPushNotificationConfigsResponse: ["configs", "nextPageToken"],
} as const;
